name: Build and Deploy HTML

on:
  push:
    branches:
      - main # 监听 `main` 分支的推送事件（可根据实际分支调整）
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3
      # Step 2: 使用 Docker 生成新的文件
      - name: Build and generate files with Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/notes:/srv/gitbook \
            fellah/gitbook:latest \
            gitbook init
          ls -alh ${{ github.workspace }}/notes
      # Step 3: 配置生成的文件并推送到目标分支
      - name: Deploy to web-html branch
        run: |
          # 设置用户信息
          git config user.name "${{ github.actor }}"
          git config user.email "nxt5656@live.cn"
          ls -alh
          # 初始化新的分支
          git switch --orphan web-html
          git reset --hard

          # 将生成的文件添加到分支
          ls -alh ${{ github.workspace }}/notes
          cp -R ${{ github.workspace }}/notes/_book .
          git add .

          # 提交更改
          git commit -m "Deploy generated files to web-html branch"

          # 强制推送到目标分支
          git push origin web-html --force